### ISSUE TITLE
[Feature request]. Ability to schedule with SLURM job_arrays.

### ISSUE THREAD

**Issue by robert-verkuil** [facebookresearch/dora#12]
Thanks again for the great tool.  Recently, I'm running Dora with many (1k - 10k) small single-gpu experiments that run for a few hours each.  Is there a way to launch these jobs via [slurm jobarray](https://slurm.schedmd.com/job_array.html)?  Otherwise scheduler load is too high.

**Comment by adefossez** [comment]
Yes this is definitely possible, I can work on that :)

**Comment by kwanUm** [comment]
Hey Alex, we are using the dora command line interface at the moment, although it's a bit hard to use due to the many lines at the table.

Our jobs are typically running a heavy model for 10-20K times in row for the purpose of optimizing protein sequences. They finish at about a few hours up to a few days (depending on the model being run).

We do need dora's resuming and cancellation capabilities and are constantly using them.
Does it req a significant change in dora?

**Comment by robert-verkuil** [comment]
We've been using this successfully on the development branch and now master.  Thanks so much @adefossez! ❤️ 
This enables us to do at-scale sweeps again, and was put together lightning-fast. 💪
